FROM python:3.5.6
WORKDIR /app
COPY . /app
ADD my_script.py /
RUN pip install pip --upgrade pip
RUN pip install numpy==1.17.0
RUN pip install opencv-python==4.1.0.25
RUN pip install matplotlib==3.0.0  
RUN pip install scikit-image==0.15.0
RUN pip install scikit-learn==0.20.0
RUN pip install scipy==1.3.0 
RUN pip install tensorflow==1.14.0
RUN pip install Keras==2.2.4
RUN pip install urllib3==1.23
RUN pip install more-itertools==4.3.0
RUN pip install jupyter
EXPOSE 8888

CMD ["jupyter", "notebook", "--ip='*'","--port=8888", "--no-browser","--allow-root"]

